server:
  port: 9999

# 指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# 服务的名称
spring:
  application:
    name: order-service
  redis:
    database: 3
    host: 172.23.0.108
    port: 6379
    timeout: 2000
  # zipkin 服务所在地址
  zipkin:
    base-url: http://localhost:9411/
  # 配置 采样百分比
  sleuth:
    sampler:
      probability: 1


# 自定义负载均衡器
product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# 开启fegin支持 hystrix
# 修改feign调用超时时间
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 4000
        readTimeout: 4000

# 把hystrix 超时时间关闭
#hystrix:
#command:
#  default:
#    execution:
#      timeout:
#        enabled: false

# 把hystrix 超时时间 设置为 4s
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

# 暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"